const char* pokeSpec[]={"None",
"Rhydon",
"Kangaskhan",
"Nidoran♂",
"Clefairy",
"Spearow",
"Voltorb",
"Nidoking",
"Slowbro",
"Ivysaur",
"Exeggutor",
"Lickitung",
"Exeggcute",
"Grimer",
"Gengar",
"Nidoran♀",
"Nidoqueen",
"Cubone",
"Rhyhorn",
"Lapras",
"Arcanine",
"Mew",
"Gyarados",
"Shellder",
"Tentacool",
"Gastly",
"Scyther",
"Staryu",
"Blastoise",
"Pinsir",
"Tangela",
"MissingNo. (Scizor)",
"MissingNo. (Shuckle)",
"Growlithe",
"Onix",
"Fearow",
"Pidgey",
"Slowpoke",
"Kadabra",
"Graveler",
"Chansey",
"Machoke",
"Mr. Mime",
"Hitmonlee",
"Hitmonchan",
"Arbok",
"Parasect",
"Psyduck",
"Drowzee",
"Golem",
"MissingNo. (Heracross)",
"Magmar",
"MissingNo. (Ho-Oh)",
"Electabuzz",
"Magneton",
"Koffing",
"MissingNo. (Sneasel)",
"Mankey",
"Seel",
"Diglett",
"Tauros",
"MissingNo. (Teddiursa)",
"MissingNo. (Ursaring)",
"MissingNo. (Slugma)",
"Farfetch'd",
"Venonat",
"Dragonite",
"MissingNo. (Magcargo)",
"MissingNo. (Swinub)",
"MissingNo. (Piloswine)",
"Doduo",
"Poliwag",
"Jynx",
"Moltres",
"Articuno",
"Zapdos",
"Ditto",
"Meowth",
"Krabby",
"MissingNo. (Corsola)",
"MissingNo. (Remoraid)",
"MissingNo. (Octillery)",
"Vulpix",
"Ninetales",
"Pikachu",
"Raichu",
"MissingNo. (Delibird)",
"MissingNo. (Mantine)",
"Dratini",
"Dragonair",
"Kabuto",
"Kabutops",
"Horsea",
"Seadra",
"MissingNo. (Skarmory)",
"MissingNo. (Houndour)",
"Sandshrew",
"Sandslash",
"Omanyte",
"Omastar",
"Jigglypuff",
"Wigglytuff",
"Eevee",
"Flareon",
"Jolteon",
"Vaporeon",
"Machop",
"Zubat",
"Ekans",
"Paras",
"Poliwhirl",
"Poliwrath",
"Weedle",
"Kakuna",
"Beedrill",
"MissingNo. (Houndoom)",
"Dodrio",
"Primeape",
"Dugtrio",
"Venomoth",
"Dewgong",
"MissingNo. (Kingdra)",
"MissingNo. (Phanpy)",
"Caterpie",
"Metapod",
"Butterfree",
"Machamp",
"MissingNo. (Donphan)",
"Golduck",
"Hypno",
"Golbat",
"Mewtwo",
"Snorlax",
"Magikarp",
"MissingNo. (Porygon2)",
"MissingNo. (Stantler)",
"Muk",
"MissingNo. (Smeargle)",
"Kingler",
"Cloyster",
"MissingNo. (Tyrogue)",
"Electrode",
"Clefable",
"Weezing",
"Persian",
"Marowak",
"MissingNo. (Hitmontop)",
"Haunter",
"Abra",
"Alakazam",
"Pidgeotto",
"Pidgeot",
"Starmie",
"Bulbasaur",
"Venusaur",
"Tentacruel",
"MissingNo. (Smoochum)",
"Goldeen",
"Seaking",
"MissingNo. (Elekid)",
"MissingNo. (Magby)",
"MissingNo. (Miltank)",
"MissingNo. (Blissey)",
"Ponyta",
"Rapidash",
"Rattata",
"Raticate",
"Nidorino",
"Nidorina",
"Geodude",
"Porygon",
"Aerodactyl",
"MissingNo. (Raikou)",
"Magnemite",
"MissingNo. (Entei)",
"MissingNo. (Suicune)",
"Charmander",
"Squirtle",
"Charmeleon",
"Wartortle",
"Charizard",
"MissingNo. (Larvitar)",
"MissingNo. Kabutops Fossil (Pupitar)",
"MissingNo. Aerodactyl Fossil (Tyranitar)",
"MissingNo. Ghost (Lugia)",
"Oddish",
"Gloom",
"Vileplume",
"Bellsprout",
"Weepinbell",
"Victreebel"};
